In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/quora-question-pairs/train.csv.zip
/kaggle/input/quora-question-pairs/sample_submission.csv.zip
/kaggle/input/quora-question-pairs/test.csv
/kaggle/input/quora-question-pairs/test.csv.zip

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pip install spacy

In [ ]:
import pandas as pd
import matplotlib.pyplot  as plt
import seaborn as sns
import numpy as np
import time 
from nltk.corpus import stopwords
from sklearn.preprocessing import normalize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

import warnings
warnings.filterwarnings('ignore')

import os
import re
import sys
from tqdm import tqdm
import spacy
# exctract word2vec vectors
# https://github.com/explosion/spaCy/issues/1721

In [ ]:
#avoiding decoding problems
df=pd.read_csv('train.csv.zip')
# encode question to unicode
# https://stackoverflow.com/a/6812069
df['question1']=df['question1'].apply(lambda x:str(x))
df['question2']=df['question2'].apply(lambda x:str(x))

In [ ]:
df.head()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

# merging text
questions = list(df['question1'])+list(df['question2'])
tf_idf=TfidfVectorizer(lowercase=False)
tf_idf.fit_transform(questions)

# dict key:word and value:tf-idf score
word2_tf_idf=dict(zip(tf_idf.get_feature_names(),tf_idf.idf_))

* After we find Tf-idf scores ,we convert each question to a weighted average of word2vec vectors by these scores 
* We are using a pre-trained **GLOVE** model which come free with "*Spacy*"(https://spacy.io/usage/vectors-similarity)
* It is trained on Wikipedia and therefore, it is stronger in terms of word semantics.

In [ ]:
# "en_vectors_web_sm", which includes over 1 million unique vectors.
nlp = spacy.load('en_core_web_sm')
vecs1 = []
for q1 in tqdm(list(df['question1'])): # tqdm is used to print the progress bar
    doc1 = nlp(q1) 
    # 
    mean_vec1 = np.zeros([len(doc1), len(doc1[0].vector)])
    for word1 in doc1:
        # word2vec
        vec1 = word1.vector
        # fetch df score
        try:
            idf = wor2_tf_idf[str(word1)]
        except:
            idf = 0
        # compute final vec
        mean_vec1 += vec1 * idf
    mean_vec1 = mean_vec1.mean(axis=0)
    vecs1.append(mean_vec1)
df['q1_feats_m'] = list(vecs1)

In [ ]:
vecs2 = []
for q2 in tqdm(list(df['question2'])): # tqdm is used to print the progress bar
    doc2 = nlp(q2) 
    # 
    mean_vec2 = np.zeros([len(doc2), len(doc2[0].vector)])
    for word2 in doc2:
        # word2vec
        vec2 = word2.vector
        # fetch df score
        try:
            idf = wor2_tf_idf[str(word2)]
        except:
            idf = 0
        # compute final vec
        mean_vec2 += vec2 * idf
    mean_vec2 = mean_vec2.mean(axis=0)
    vecs2.append(mean_vec2)
df['q2_feats_m'] = list(vecs2)

In [18]:
#preprocessing_features_train.csv(Simple Preprocessng Features)
#nlp_features_train.csv(NLP FEATURES)
if os.path.isfile("nlp_features_train.csv"):
    df_nlp=pd.read_csv('/content/drive/MyDrive/Quora Question Pairs/nlp_features_train.csv',encoding='latin-1')
else:
    print('download nlp_features_train.csv or run prevous notebook')

if os.path.isfile('/content/drive/MyDrive/Quora Question Pairs/df_fe_without_preprocessing_train.csv'):
    df_pre_process=pd.read_csv('/content/drive/MyDrive/Quora Question Pairs/df_fe_without_preprocessing_train.csv',encoding='latin-1')
else:
    print('run prevous notebook')

In [28]:
df1=df_nlp.drop(['qid1','qid2','question1','question2'],axis=1)
df2=df_pre_process.drop(['qid1','qid2','question1','question2','is_duplicate'],axis=1)
df3=df.drop(['qid1','qid2','question1','question2','is_duplicate'],axis=1)
df3_q1 = pd.DataFrame(df3.q1_feats_m.values.tolist(), index= df3.index)
df3_q2 = pd.DataFrame(df3.q2_feats_m.values.tolist(), index=df3.index)

In [22]:
df1.head()

   id  is_duplicate  ...  fuzz_partial_ratio  longest_substr_ratio
0   0             0  ...                 100              0.982759
1   1             0  ...                  75              0.596154
2   2             0  ...                  47              0.166667
3   3             0  ...                  14              0.039216
4   4             0  ...                  56              0.175000

[5 rows x 17 columns]

In [23]:
df2.head()

   id  freq_qid1  freq_qid2  ...  word_share  freq_q1+q2  freq_q1-q2
0   0          1          1  ...    0.434783           2           0
1   1          4          1  ...    0.200000           5           3
2   2          1          1  ...    0.166667           2           0
3   3          1          1  ...    0.000000           2           0
4   4          3          1  ...    0.100000           4           2

[5 rows x 12 columns]

In [24]:
df3_q1.head()

    0    1    2    3    4    5    6   ...   89   90   91   92   93   94   95
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 96 columns]

In [29]:
df3_q2.head()

    0    1    2    3    4    5    6   ...   89   90   91   92   93   94   95
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 96 columns]

In [27]:
print("Number of features in nlp dataframe:",df1.shape[1])
print("Number of features in preprocessed dataframe",df2.shape[1])
print("Number of features in question1 w2v dataframe",df3_q1.shape[1])
print("Number of features in question1 w2v dataframe ",df3_q2.shape[1])
print("Number of features in final data frame",df1.shape[1]+df2.shape[1]+df3_q1.shape[1]+df3_q1.shape[1])

Number of features in nlp dataframe: 17
Number of features in preprocessed dataframe 12
Number of features in question1 w2v dataframe 96
Number of features in question1 w2v dataframe  96
Number of features in final data frame 221